### ISSUE TITLE
brush update:  Failed to get available update data

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drop#10]
This is for Brush version https://github.com/backdrop-contrib/brush/archive/1.x-1.3.tar.gz 

`brush dl` works, but `brush up` doesn't?

Anything I should check?

Best,
Michael

```
inetd@srv10 [~/public_html/idadev]# brush dl ckeditor_accordion

Project ckeditor_accordion (1.x-1.0.0-beta) downloaded to /home/inetd/public_html/idadev/./modules/ckeditor_accordion.      [success]
```

```
inetd@srv10 [~/public_html/idadev]# brush en update
update is already enabled.                                                                                                  [ok]

inetd@srv10 [~/public_html/idadev]# brush -n up
Failed to get available update data for one project.                                                                        [error]
Update information last refreshed: Never

Update status information on all installed and enabled Backdrop projects:
 Name         Installed version  Proposed version  Status
 Backdrop     1.17.0             1.17.0            Up to date
 Entity Plus  1.x-1.0.9          1.x-1.0.9         Up to date
 Entity UI    1.x-1.0.0-beta     1.x-1.0.0-beta    Up to date
 Rules        1.x-2.1.5          1.x-2.1.5         Up to date


No code updates available.                                                                                                  [ok]


inetd@srv10 [~/public_html/idadev]# brush up backdrop
Failed to get available update data for one project.                                                                        [error]
Update information last refreshed: Never

Update status information on all installed and enabled Backdrop projects:
 Name         Installed version  Proposed version  Status
 Backdrop     1.17.0             1.17.0            Up to date
 Entity Plus  1.x-1.0.9          1.x-1.0.9         Up to date
 Entity UI    1.x-1.0.0-beta     1.x-1.0.0-beta    Up to date
 Rules        1.x-2.1.5          1.x-2.1.5         Up to date


No code updates available.                                                                                                  [ok]


inetd@srv10 [~/public_html/idadev]# brush up rules
Failed to get available update data for one project.                                                                        [error]
Update information last refreshed: Never

Update status information on all installed and enabled Backdrop projects:
 Name         Installed version  Proposed version  Status
 Backdrop     1.17.0             1.17.0            Up to date
 Entity Plus  1.x-1.0.9          1.x-1.0.9         Up to date
 Entity UI    1.x-1.0.0-beta     1.x-1.0.0-beta    Up to date
 Rules        1.x-2.1.5          1.x-2.1.5         Up to date


No code updates available.                                                                                                  [ok]


inetd@srv10 [~/public_html/idadev]# brush status
 Backdrop version                 :  1.17.0
 Site URI                         :  http://idadev
 Database driver                  :  mysql
 Database hostname                :  127.0.0.1
 Database username                :  inetd_idadev
 Database name                    :  inetd_idadev
 Database                         :  Connected
 Backdrop bootstrap               :  Successful
 Backdrop user                    :  Anonymous
 Default theme                    :  Basis
 Administration theme             :  Seven
 PHP configuration                :  /opt/cpanel/ea-php73/root/etc/php.ini
 Brush script                     :  /usr/local/bin/php /home/common/bin/brush/brush.php --php='/usr/local/bin/php'
 Brush version                    :  1.x-1.1
 Brush alias files                :  /home/common/bin/brush/includes/../mysite.aliases.brushrc.php
 Backdrop root                    :  /home/inetd/public_html/idadev
 Site path                        :  .
 Modules path                     :  ./modules
 Themes path                      :  ./themes
 Files directory path             :  files
 Temporary files directory path   :  /tmp
 Private files directory path     :  files/private
 Install profile                  :  standard

```

**Comment by ghost** [comment]
This bug is dependent on:

Rename vset commands respectively to config-list, config-set, config-get commands #2

```
brush-1.x-1.3/commands/pm/update_info/backdrop.inc
Line 37:   return variable_get('update_last_check', 0);

```

**Comment by alanmels** [comment]
Hey Michael,

The `brush up` command has been fixed by https://github.com/backdrop-contrib/brush/commit/311e673ca2774c555bcdb122be5b5562675aaeed. Please run some tests.

**Comment by ghost** [comment]
Hi Alan,

It seems fine to me.  I’ve attached the output stream for reference.

I had two issues.  I’m not sure either is related to `brush up` though.

First, I used the git command to get `brush`’s HEAD for testing (command bd for brush-dev in attached).*  I used wget and unpacked the tarball for brush [version 1.1 - 1.3, not sure which at this point] (command brush in attached).  And got this error every time I ran brush (HEAD):

`fatal: not a git repository (or any of the parent directories): .git`

* Is there a git cheat sheet you recommend?  I’m guessing there’s a way to git clone only the `311e673` branch?  Which would have made testing more concrete.

Second, I noticed a:

`Failed to get available update data for one project.`

but, I think that’s from having CiviCRM enabled?

Otherwise works well and thank you!

Michael

Edit:

Maybe a third thing? Brush version comes up blank on the git clone HEAD.

`Brush version                    :`
 
Is it suppose to be that way?

[brush-testing-20201012.txt](https://github.com/backdrop-contrib/brush/files/5368071/brush-testing-20201012.txt)

**Comment by alanmels** [comment]
@Michael-IDA,

Thanks for your feedback, however for posterity reasons I have to ask you not to pile multiple issues into one discussion, but concentrate on the subject matter instead. It's in your own best interest not to confuse different issues - will be much easier to re-visit/search/browse issues in the future.

So I have to close this issue with only one suggestion to give: please make sure to delete the existing directory for the module before cloning the module from afresh.

**Comment by ghost** [comment]
Hi Alan,

> please make sure to delete the existing directory for the module before cloning the module from afresh.

There was no brush-dev directory before I issued the:

`inetd@srv10 [/home/common/bin]# git clone https://github.com/backdrop-contrib/brush.git brush-dev`

Sorry for not making that clear.

> I have to ask you not to pile multiple issues into one discussion, but concentrate on the subject matter instead.

Yeah, use to doing these things through email.

And before I waste more of your time by opening additional tickets, are any of the three issues?

Best,
Michael

**Comment by alanmels** [comment]
> And before I waste more of your time by opening additional tickets, are any of the three issues?

Not sure if I've got your point. 

The problem is that I just see the text describing mixed issues, and I really can't be trying to identify issues and separate them to three different ones. Just try to report each problem on their own issues.
