### ISSUE TITLE
ArgumentCountError: Too few arguments to function brush_error_handler

### ISSUE THREAD

**Issue by leeksoup** [backdrop-contrib/drop#27]
brush used to work just fine, but the last couple weeks it's been giving errors for any and all commands. E.g.

```
$ brush status core
WD php: ArgumentCountError: Too few arguments to function            [error]
brush_error_handler(), 4 passed and exactly 5 expected in
brush_error_handler() (line 393 of
/usr/local/src/brush/includes/environment.inc).
ArgumentCountError: Too few arguments to function brush_error_handler(), 4 passed and exactly 5 expected in brush_error_handler() (line 393 of /usr/local/src/brush/includes/environment.inc).
Brush command terminated abnormally due to an unrecoverable error.   [error]
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function brush_error_handler(), 4 passed and exactly 5 expected in /usr/local/src/brush/includes/environment.inc:393
Stack trace:
#0 /usr/local/src/brush/includes/brush.inc(2824): brush_error_handler()
#1 /usr/local/src/brush/includes/environment.inc(462): brush_memory_limit()
#2 /usr/local/src/brush/brush.php(178): _brush_postmortem()
#3 [internal function]: brush_shutdown()
#4 {main}
  thrown in /usr/local/src/brush/includes/environment.inc on line 393
```

The only thing I can think that I changed was that I updated the php version from 7.4 to 8.1. Could that be the source of the problem?

**Comment by izmeez** [comment]
Same issue Fatal error with php 8.1.17 tested brush using the latest code with recent commits.

**Comment by alanmels** [comment]
Had no idea that somebody else was using Brush as we, at AltaGrade, are gradually switching to [Bee](https://github.com/backdrop-contrib/bee). 

Do you, guys, have specific reason why you keep using Brush rather than Bee? What exact features Bee is missing for you that Brush has?

I'm asking this questions to facilitate quick introduction of the missing features to Bee instead of spending time fixing Brush. If the list is too long (because Brush has everything that pre-composer era Drush did) then probably, we need to fix it here for now.

**Comment by izmeez** [comment]
No, we do not have specific reason for using brush. Just doing due diligence testing options for backdrop: bee, drush and brush. Bee is clearly where the future lies. If brush is removed it won't affect us. Drush is withering on the web. It was good for "drush make" although there were plans to remove that and it's not an option in Bee. Our alternative to drush make is to just go straight back to script files and avoid dependency on others.

**Comment by alanmels** [comment]
https://github.com/backdrop-contrib/brush/blob/1.x-1.x/README.md
