### ISSUE TITLE
Explain in readme when someone wants to use this instead of drush or b

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/drop#3]
This will help people when they're trying to decide which project to use.

**Comment by alanmels** [comment]
@herbdool, you are right - not everybody will look at https://forum.backdropcms.org/forum/drop-command-line-shell-and-unix-scripting-interface-backdrop-cms I'll add comparison information soon.

**Comment by alanmels** [comment]
Fixed by https://github.com/backdrop-contrib/brush/commit/1101e9b0403263162394e8b5caa8c7d6f1293def
