### ISSUE TITLE
Rename Drop to Brush

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/drop#4]
Unfortunately, the `drop` name was not a good and thought-through choice, because sometimes it causes ambiguity. For example, when using it with the same name command arguments as:

```
drop sql-drop
```

This project is not used by anyone else, but AltaGrade team and as explained on https://forum.backdropcms.org/forum/drop-command-line-shell-and-unix-scripting-interface-backdrop-cms it was rolled out just to share with community in case if someone else needed it. We are using https://github.com/altagrade/brush anyway, so would be nice to sync it with this project.

I wanted to rename this per https://help.github.com/en/github/administering-a-repository/renaming-a-repository, but apparently do not have enough access level.

**Comment by stpaultim** [comment]
Just in case you haven't seen this discussion, I thought it might be relevant here.
https://github.com/backdrop-contrib/drush/issues/184

**Comment by serundeputy** [comment]
I've renamed the project to brush.

**Comment by alanmels** [comment]
> Just in case you haven't seen this discussion, I thought it might be relevant here.
> [backdrop-contrib/drush#184](https://github.com/backdrop-contrib/drush/issues/184)

@stpaultim, I've seen it, but thought that they didn't like the idea, so wanted to take over the name if it's still available.

**Comment by alanmels** [comment]
> I've renamed the project to brush.

Thanks, @serundeputy!
