### ISSUE TITLE
brush: Permission denied

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/drop#8]
brush was pushed with the wrong permissions?  It no longer just unpacks and goes...

I guess, give a quick scan to see if any other file(s) need permission fixes.

Best,
Michael

```
inetd@srv10 [/home/common/bin]# wget https://github.com/backdrop-contrib/brush/releases/download/1.x-1.2/brush.zip
--2020-08-06 17:48:45--  https://github.com/backdrop-contrib/brush/releases/download/1.x-1.2/brush.zip

inetd@srv10 [/home/common/bin]# mv brush brush.20200806-174914
inetd@srv10 [/home/common/bin]# unzip brush.zip
inetd@srv10 [/home/common/bin]# brush status
-bash: /home/common/bin/brush/brush: Permission denied
inetd@srv10 [/home/common/bin]# cd brush
inetd@srv10 [/home/common/bin/brush]# ll
total 176
drwxr-xr-x 7 inetd inetd  4096 Aug  6 17:49 .
drwx------ 7 inetd inetd  4096 Aug  6 17:49 ..
-rw-rw-rw- 1 inetd inetd  3361 Jun  3 09:30 brush

```

**Comment by ghost** [comment]
Uhm? What am I missing?

```
inetd@srv10 [/home/common/bin/brush]# chmod +x brush
inetd@srv10 [/home/common/bin/brush]# cd ..
inetd@srv10 [/home/common/bin]# brush status
 PHP configuration   :  /opt/cpanel/ea-php73/root/etc/php.ini
 Brush script        :  /usr/local/bin/php /home/common/bin/brush/brush.php --php='/usr/local/bin/php'
 Brush version       :  1.x-1.1
 Brush alias files   :  /home/common/bin/brush/includes/../mysite.aliases.brushrc.php

```
Why's the version still 1.1 when it downloaded 1.2?

(No pun intended)
Maybe I don't get github?

Edit:  For completeness

```
inetd@srv10 [~]# alias brush
alias brush='/home/common/bin/brush/brush'
inetd@srv10 [~]# rel
CentOS Linux release 7.8.2003 (Core)
Linux srv10.srv10-inet-design.com 3.10.0 #1 SMP Mon Dec 9 19:36:21 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by alanmels** [comment]
Hi Michael,

Sorry for late response. I've just run the following commands:

```
	sudo git clone https://github.com/backdrop-contrib/brush.git /var/www/brush
	sudo ln -s /var/www/brush/brush /usr/local/bin/brush
```

from my local environment and everything works fine to me:

```
brush st
 Backdrop version                 :  1.18.x-dev                                                             
 Site URI                         :  http://docroot                                                         
 Database driver                  :  mysql                                                                  
 Database hostname                :  db                                                                     
 Database username                :  user                                                                   
 Database name                    :  default                                                                
 Database                         :  Connected                                                              
 Backdrop bootstrap               :  Successful                                                             
 Backdrop user                    :  Anonymous                                                              
 Default theme                    :  Altaback                                                               
 Administration theme             :  Seven                                                                  
 PHP configuration                :  /usr/local/etc/php/php.ini                                             
 Brush script                     :  /usr/local/bin/php /var/www/brush/brush.php --php='/usr/local/bin/php' 
 Brush version                    :  1.x-1.1                                                                
 Brush alias files                :  /var/www/brush/includes/../mysite.aliases.brushrc.php                  
 Backdrop root                    :  /var/www/docroot                                                       
 Site path                        :  .                                                                      
 Modules path                     :  ./modules                                                              
 Themes path                      :  ./themes                                                               
 Files directory path             :  files                                                                  
 Temporary files directory path   :  /tmp                                                                   
 Private files directory path     :                                                                         
 Install profile                  :  standard    
```

**Comment by ghost** [comment]
Hi Alan,

Page: https://github.com/backdrop-contrib/brush
Shows: Releases, 1.x-1.2 Latest, on Jun 3

Your `git clone` is showing 

`Brush version                    :  1.x-1.1`

Which is what the .zip for `1.x-1.2` I downloaded was showing above, so yeah it seems like the 1.2 was just packaged wrong???  And has now been regressed???

Oddly the .zip download link on the above page (under ‘Code’) now shows

https://github.com/backdrop-contrib/brush/archive/1.x-1.x.zip

AFAIR that was the link that I got the 1.2 .zip from, so that’s been changed too?

I guess I’m left with these questions:

- What version of Brush is the latest ‘production’ so to speak. 
- Where does one find that information in github?
- What’s the proper place to pull ‘production’ .zip’s from?

Best,
Michael

PS:

I have not check anything yet, but is this known already?    If it is a unknown bug I don’t mind doing the work to report it, just don’t want to waste anyone’s time if it just an artifact of this 1.1 vs. 1.2 thing...

```
inetd@srv10 [~/public_html/idadev]# brush status
 Backdrop version                 :  1.17.0
 Site URI                         :  http://idadev
 Database driver                  :  mysql
 Database hostname                :  127.0.0.1
 Database username                :  inetd_idadev
 Database name                    :  inetd_idadev
 Database                         :  Connected
 Backdrop bootstrap               :  Successful
 Backdrop user                    :  Anonymous
 Default theme                    :  Basis
 Administration theme             :  Seven
 PHP configuration                :  /opt/cpanel/ea-php73/root/etc/php.ini
 Brush script                     :  /usr/local/bin/php /home/common/bin/brush/brush.php --php='/usr/local/bin/php'
 Brush version                    :  1.x-1.1
 Brush alias files                :  /home/common/bin/brush/includes/../mysite.aliases.brushrc.php
 Backdrop root                    :  /home/inetd/public_html/idadev
 Site path                        :  .
 Modules path                     :  ./modules
 Themes path                      :  ./themes
 Files directory path             :  files
 Temporary files directory path   :  /tmp
 Private files directory path     :  files/private
 Install profile                  :  standard

inetd@srv10 [~/public_html/idadev]# brush en update
update is already enabled.                                                                                                  [ok]
There were no extensions that could be enabled.                                                                             [ok]

inetd@srv10 [~/public_html/idadev]# brush -n up
Unable to include the update_info engine backdrop from /home/common/bin/brush/commands/pm/update_info.                      [error]
WD php: Error: Call to undefined function _pm_get_update_info() in brush_pm_updatecode() (line 30 of                        [error]
/home/common/bin/brush/commands/pm/updatecode.pm.inc).
Error: Call to undefined function _pm_get_update_info() in brush_pm_updatecode() (line 30 of /home/common/bin/brush/commands/pm/updatecode.pm.inc).
Brush command terminated abnormally due to an unrecoverable error.                                                          [error]

```

**Comment by alanmels** [comment]
> Page: https://github.com/backdrop-contrib/brush
> Shows: Releases, 1.x-1.2 Latest, on Jun 3
> 
> Your `git clone` is showing
> 
> `Brush version : 1.x-1.1`
> 
> Which is what the .zip for `1.x-1.2` I downloaded was showing above, so yeah it seems like the 1.2 was just packaged wrong??? And has now been regressed???

Releases listed on https://github.com/backdrop-contrib/brush/releases are for the main Backdrop CMS portal to be able to pull information from GitHub. In particular, the https://backdropcms.org/project/brush page always pulls the latest official release from the module's repository on GitHub. And that's true for all other Backdrop projects: their repositories are  actually located on GitHub, but every time a new release is drafted respective download and source files in .zip and tar.gz format are automatically packaged and pulled by https://backdropcms.org/modules.

And it is totally up to you which version to use. The latest official release of any module is usually more stable and is recommended for production sites. However, if you are a developer and would like to get the latest development branch, then I'd suggest to always clone the code with `git clone https://github.com/backdrop-contrib/brush.git`.

> AFAIR that was the link that I got the 1.2 .zip from, so that’s been changed too?

I've fixed some bugs and released another 1.x-1.3 version just today, so don't think there were much difference between 1.2 and the dev branch before today. And I believe the initially reported "Permission denied" error is about your local environment, so make sure to work as a user with enough privileges or use `sudo` to avoid that kind of errors.

>     * What version of Brush is the latest ‘production’ so to speak.

As I tried to explain above, it's not only for Brush, but for every other Backdrop project: the development branch on GitHub (sometimes called HEAD) is the latest one. To get the latest version, go to https://github.com/backdrop-contrib, select a project, click on the green `Code` drop-down button, copy the link and clone it. 
 
>     * Where does one find that information in github?

Just got to any Backdrop contributed module's GitHub page and you'll find all the information there. For example, https://github.com/backdrop-contrib/brush

>     * What’s the proper place to pull ‘production’ .zip’s from?

As explained above, if you are a developer and ok to work with the current development branch, then just use the `git clone https://github.com/backdrop-contrib/brush.git` command. If you prefer .zip file, then just download it as shown on the screenshot:

![get_zip](https://user-images.githubusercontent.com/56604405/94245944-3ee7ef80-fed8-11ea-8f2a-92f71b7b774a.jpg)


> I have not check anything yet, but is this known already? If it is a unknown bug I don’t mind doing the work to report it, just don’t want to waste anyone’s time if it just an artifact of this 1.1 vs. 1.2 thing...
> ...
> Unable to include the update_info engine backdrop from /home/common/bin/brush/commands/pm/update_info.                      [error]
> WD php: Error: Call to undefined function _pm_get_update_info() in brush_pm_updatecode() (line 30 of                        [error]
> /home/common/bin/brush/commands/pm/updatecode.pm.inc).
> Error: Call to undefined function _pm_get_update_info() in brush_pm_updatecode() (line 30 of /home/common/bin/brush/commands/pm/updatecode.pm.inc).
> Brush command terminated abnormally due to an unrecoverable error.                                                          [error]
> ```

Always try to search open and closed issues on https://github.com/backdrop-contrib/brush/issues. This one was spotted back on June 9 https://github.com/backdrop-contrib/brush/issues/7, but I just didn't have time to fix it until today.

And since the Brush module does not deal with any permissions on your local environment, I have to close this issue. Feel free to create new issues.

**Comment by ghost** [comment]
Hi Alan,

If my post are coming across as combative, they’re not intended that way.

Background:

I’ve been using

- *Nix/Bash for 25+ years
- Drupal/PHP for ~15 years
- Drush for ~10 years

AFAIK Backdrop is the Drupal 7 port that doesn’t go the route of inhibiting users by forcing composer, lando, git, symfony, etc. upon them.  Thereby specifically not excluding the vast majority of ‘regular people.’  The page you’ve linked to https://backdropcms.org/project/brush seems to be forcing users to know git to install Brush?  There are no .zip’s or tarballs linked to on that page.

And that’s it in a nutshell, I came from that page to github looking for how to download the tarball of the Brush ‘production’ (latest) release.  I am specifically not looking for the development (HEAD) release.

I do appreciate the clarification of how github differs from the way Drupal.org identifies production/development releases.  (Yeah that would have been my guess, but it’s very helpful to have someone who actually knows nail it down.)

Okay, using your screenshot:

The github home for Brush https://github.com/backdrop-contrib/brush has (what the red arrow points to) what appears to be the generally expected way of downloading the ‘production’ release of Brush as a regular compressed file (the traditional way of installing Drupal/Backdrop/Drush/etc.) in the green ‘Code’ drop down under ‘Download ZIP.’  But, that link goes to an archival copy of Brush version 1.x (archive/1.x-1.x.zip).  (I even opened a completely different browser in case there was some odd browser cache issue.)

That is what I was attempting to point out in my last post.  Github seems ‘broken.’

But, literally, I don’t know.  I don’t use git/github, so that’s why I’m asking...

I can find a tarball of Brush 1.3 through the ‘Latest’ link in the ‘Releases’ section (basically the start of the red arrow in your screenshot), and if that is the normal way of downloading them, then I’m cool with that.

Again, I just want to know what’s what.  Is it the green Code section (which happens to be currently broken), is it the ‘Releases’ section, or is there a global URL (like ‘HEAD’ but for ‘Latest Release’)?

Best,
Michael

PS:
Possible the only part of this post related to the OP...

Pulling the HEAD to check a file permission on a specific release version isn’t valid methodology...  Just say’in.

It is not an issue in this tarball, https://github.com/backdrop-contrib/brush/archive/1.x-1.3.tar.gz

**Comment by alanmels** [comment]
> If my post are coming across as combative, they’re not intended that way.

Hi Michael,

It's totally ok until you get used to everything. My only concern is that sometimes I am so busy that I can't be as prompt as I wish. I also can't help you with something that is totally out of my hands. 

For example you say:

> The page you’ve linked to https://backdropcms.org/project/brush seems to be forcing users to know git to install Brush? There are no .zip’s or tarballs linked to on that page.

I can't comment anything on how backdropcms.org works. If you would like to see zipped files on project pages, then you need to file a feature request on https://github.com/backdrop-ops/backdropcms.org/issues.

> ... in the green ‘Code’ drop down under ‘Download ZIP.’ But, that link goes to an archival copy of Brush version 1.x (archive/1.x-1.x.zip). (I even opened a completely different browser in case there was some odd browser cache issue.)

I understand where your confusion is coming from - when you copy the zipped version from https://github.com/backdrop-contrib/brush, then it has `archive` in the URL https://github.com/backdrop-contrib/brush/archive/1.x-1.x.zip. Well, that's again how GitHub decided to construct their paths to projects, in fact 1.x-1.x is not `archival copy` (you probably mean old or outdated), but the most up-to-date, development (HEAD) version for Brush (or for any other project for that matter). If you are looking for official releases then they are listed on https://github.com/backdrop-contrib/brush/releases. 

> That is what I was attempting to point out in my last post. Github seems ‘broken.’

Well, you wouldn't be as confused if you had try to download some other projects from GitHub. Try any project listed on https://github.com/backdrop-contrib and you will see they are all 'broken'.

> But, literally, I don’t know. I don’t use git/github, so that’s why I’m asking...

I understand, but Backdrop community decided to go with GitHub and that's why we all have to adjust to be able to efficiently work with Backdrop projects. 

> I can find a tarball of Brush 1.3 through the ‘Latest’ link in the ‘Releases’ section (basically the start of the red arrow in your screenshot), and if that is the normal way of downloading them, then I’m cool with that.

I am afraid there is no other way, but to learn navigating through GitHub user interface. Please look at the screenshot where the releases link:

![releases](https://user-images.githubusercontent.com/56604405/94491144-e26d2480-01a4-11eb-9141-d71d0b5806ff.jpg)

If you click on `+3 releases` link then you'll find yourself at https://github.com/backdrop-contrib/brush/releases where you can download any version of the module.

> Pulling the HEAD to check a file permission on a specific release version isn’t valid methodology... Just say’in.

Unfortunately, the module can not manage permission issues on your local environment. Please read step 2 on https://github.com/backdrop-contrib/brush/releases
